"""Initial migration

Revision ID: 94ade65d94d5
Revises: 
Create Date: 2025-12-17 22:27:46.835364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ade65d94d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_attacks', sa.Integer(), nullable=True),
    sa.Column('successful_attacks', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_reports_id'), 'test_reports', ['id'], unique=False)
    op.create_index(op.f('ix_test_reports_test_id'), 'test_reports', ['test_id'], unique=True)
    op.create_table('attack_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attack_id', sa.String(), nullable=False),
    sa.Column('attack_type', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('detection_score', sa.Float(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['test_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_results_attack_id'), 'attack_results', ['attack_id'], unique=True)
    op.create_index(op.f('ix_attack_results_id'), 'attack_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attack_results_id'), table_name='attack_results')
    op.drop_index(op.f('ix_attack_results_attack_id'), table_name='attack_results')
    op.drop_table('attack_results')
    op.drop_index(op.f('ix_test_reports_test_id'), table_name='test_reports')
    op.drop_index(op.f('ix_test_reports_id'), table_name='test_reports')
    op.drop_table('test_reports')
    # ### end Alembic commands ###
