"""Remove unique constraint from attack_id in attack_results

Revision ID: f9318b588a7d
Revises: 94ade65d94d5
Create Date: 2025-12-18 08:24:04.911434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9318b588a7d'
down_revision: Union[str, None] = '94ade65d94d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attack_results_attack_id', table_name='attack_results')
    op.create_index(op.f('ix_attack_results_attack_id'), 'attack_results', ['attack_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attack_results_attack_id'), table_name='attack_results')
    op.create_index('ix_attack_results_attack_id', 'attack_results', ['attack_id'], unique=False)
    # ### end Alembic commands ###
